CREATE DATABASE Gimnasio;

CREATE TABLE Cliente(
  IDCliente INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  Nombre VARCHAR(255) NOT NULL,
  ApellidoP VARCHAR(255) NOT NULL,
  ApellidoM VARCHAR(255),

);

CREATE TABLE Suscripcion(
  
);